name: Build for Linux

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  app-image:
    name: AppImage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install ARM libraries
        if: ${{ matrix.arch == 'aarch64' }}
        run: sudo apt install gcc-aarch64-linux-gnu

      - name: Add target
        run: rustup target add ${{ matrix.arch }}-unknown-linux-gnu

      - name: Build executable
        run: cargo b --release --target ${{ matrix.arch }}-unknown-linux-gnu

      - name: Download AppImageTool
        run: curl -Lo ./appimagetool.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-${{ matrix.arch }}.AppImage && chmod +x ./appimagetool.AppImage

      - name: Build AppImage
        run: ARCH=${{ matrix.arch }} ./appimagetool.AppImage -n ./packaging/linux/SortPhoto.AppDir ./packaging/linux/sortphoto-${{ matrix.arch }}.AppImage

      - name: Upload arm appimage to Cloudflare R2
        uses: randomairborne/r2-release@v1
        with:
          endpoint: ${{ secrets.S3_ENDPOINT }}
          accesskeyid: ${{ secrets.S3_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucket: 'valkyrie-download-store'
          file: './packaging/linux/sortphoto-${{ matrix.arch }}.AppImage'
          destination: 'sortphoto/sortphoto-${{ matrix.arch }}.AppImage'

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          dnf -y install docker

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: palette.flatpak
          manifest-path: sh.valk.SortPhoto.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}

      - uses: flatpak/flatpak-github-actions/flat-manager@v4
        name: "Deploy"
        with:
          repository: ${{ secrets.FLATPAK_ACCESS_KEY }}
          flat-manager-url: https://flatpak-api.elementary.io
          token: some_very_hidden_token