name: Build for Linux

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  app-image:
    name: AppImage
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # Add aarch64 if you can figure out how to make it work
        arch: [x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.arch }}-unknown-linux-gnu

      - name: Install dependencies
        run: sudo apt-get install -y libgtk-3-dev libfontconfig-dev

      - name: Build executable
        run: cargo build --release

      - name: Download AppImageTool
        run: curl -Lo ./appimagetool.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-${{ matrix.arch }}.AppImage && chmod +x ./appimagetool.AppImage

      - name: Build AppImage
        run: ARCH=${{ matrix.arch }} ./appimagetool.AppImage -n ./packaging/linux/SortPhoto.AppDir ./packaging/linux/sortphoto-${{ matrix.arch }}.AppImage

      - name: Upload ${{ matrix.arch }} appimage to Cloudflare R2
        uses: randomairborne/r2-release@v1
        with:
          endpoint: ${{ secrets.S3_ENDPOINT }}
          accesskeyid: ${{ secrets.S3_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucket: 'valkyrie-download-store'
          file: './packaging/linux/sortphoto-${{ matrix.arch }}.AppImage'
          destination: 'sortphoto/sortphoto-${{ matrix.arch }}.AppImage'
